/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Clinic = IDL.Record({
  'id' : IDL.Text,
  'hours' : IDL.Text,
  'mapLink' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'bookingUrl' : IDL.Opt(IDL.Text),
  'contactDetails' : IDL.Text,
});
export const WebsiteImage = IDL.Record({
  'id' : IDL.Text,
  'darkModeImage' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'image' : ExternalBlob,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const SocialMediaLink = IDL.Record({
  'url' : IDL.Text,
  'displayName' : IDL.Text,
  'order' : IDL.Nat,
  'icon' : IDL.Opt(ExternalBlob),
  'platform' : IDL.Text,
  'iconSize' : IDL.Nat,
  'isVisible' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Config = IDL.Record({
  'terms' : IDL.Text,
  'canonicalUrl' : IDL.Text,
});
export const DoctorCredentials = IDL.Record({
  'yearsOfExperience' : IDL.Text,
  'profileImage' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'qualifications' : IDL.Text,
  'achievements' : IDL.Text,
  'specializations' : IDL.Text,
});
export const FooterContact = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const FooterLink = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
export const FooterContent = IDL.Record({
  'contact' : FooterContact,
  'background' : IDL.Opt(ExternalBlob),
  'quickLinks' : IDL.Vec(FooterLink),
  'copyright' : IDL.Text,
});
export const VerticalPosition = IDL.Variant({
  'top' : IDL.Null,
  'center' : IDL.Null,
  'bottom' : IDL.Null,
});
export const TextSizePreset = IDL.Variant({
  'large' : IDL.Null,
  'extraLarge' : IDL.Null,
  'medium' : IDL.Null,
});
export const MaxWidthPreset = IDL.Variant({
  'full' : IDL.Null,
  'large' : IDL.Null,
  'medium' : IDL.Null,
});
export const HorizontalAlignment = IDL.Variant({
  'center' : IDL.Null,
  'left' : IDL.Null,
  'right' : IDL.Null,
});
export const CTARowLayout = IDL.Variant({
  'row' : IDL.Null,
  'stacked' : IDL.Null,
});
export const HeroLayoutOverride = IDL.Record({
  'verticalPlacement' : VerticalPosition,
  'textSizePreset' : TextSizePreset,
  'contentContainerPreset' : MaxWidthPreset,
  'explicitMaxWidth' : IDL.Opt(IDL.Nat),
  'horizontalAlignment' : HorizontalAlignment,
  'ctaRowLayout' : CTARowLayout,
});
export const Color = IDL.Record({
  'red' : IDL.Nat,
  'blue' : IDL.Nat,
  'green' : IDL.Nat,
});
export const Gradient = IDL.Record({
  'direction' : IDL.Variant({
    'topToBottom' : IDL.Null,
    'leftToRight' : IDL.Null,
  }),
  'colors' : IDL.Vec(Color),
  'intensity' : IDL.Nat,
});
export const ThemeType = IDL.Record({
  'accent' : IDL.Variant({
    'magenta' : IDL.Null,
    'blue' : IDL.Null,
    'teal' : IDL.Null,
  }),
  'mode' : IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null }),
  'gradientStyle' : IDL.Variant({ 'radial' : IDL.Null, 'linear' : IDL.Null }),
});
export const AreaDimensions = IDL.Record({
  'height' : IDL.Nat,
  'width' : IDL.Nat,
});
export const Position = IDL.Record({ 'x' : IDL.Int, 'y' : IDL.Int });
export const Glassmorphism = IDL.Record({
  'transparency' : IDL.Nat,
  'blurIntensity' : IDL.Nat,
  'overlayEffect' : IDL.Variant({
    'strong' : IDL.Null,
    'subtle' : IDL.Null,
    'medium' : IDL.Null,
  }),
});
export const Spacing = IDL.Record({
  'verticalPadding' : IDL.Nat,
  'elementSpacing' : IDL.Nat,
  'contentAlignment' : IDL.Variant({
    'center' : IDL.Null,
    'left' : IDL.Null,
    'right' : IDL.Null,
  }),
});
export const ColorAccents = IDL.Record({
  'secondary' : Color,
  'primary' : Color,
});
export const MotionPattern = IDL.Record({
  'complexity' : IDL.Nat,
  'patternType' : IDL.Variant({
    'wave' : IDL.Null,
    'bounce' : IDL.Null,
    'random' : IDL.Null,
    'spiral' : IDL.Null,
  }),
});
export const MotionAmplitude = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const MotionSpeed = IDL.Variant({
  'fast' : IDL.Null,
  'slow' : IDL.Null,
  'medium' : IDL.Null,
});
export const MotionEffectType = IDL.Variant({
  'waveMotion' : IDL.Null,
  'floatingMotion' : IDL.Null,
  'wave' : IDL.Null,
  'bounce' : IDL.Null,
  'random' : IDL.Null,
  'spiral' : IDL.Null,
});
export const MotionEffect = IDL.Record({
  'pattern' : MotionPattern,
  'amplitude' : MotionAmplitude,
  'enabled' : IDL.Bool,
  'speed' : MotionSpeed,
  'effectType' : MotionEffectType,
});
export const EffectSpeed = IDL.Variant({
  'fast' : IDL.Null,
  'slow' : IDL.Null,
  'medium' : IDL.Null,
});
export const ParticleEffectType = IDL.Variant({
  'confetti' : IDL.Null,
  'dots' : IDL.Null,
  'crossParticles' : IDL.Null,
  'bubbles' : IDL.Null,
  'lines' : IDL.Null,
  'sparkles' : IDL.Null,
  'swirls' : IDL.Null,
  'stethoscopeParticles' : IDL.Null,
  'rings' : IDL.Null,
});
export const EffectIntensity = IDL.Variant({
  'dynamic' : IDL.Null,
  'subtle' : IDL.Null,
  'moderate' : IDL.Null,
});
export const ColorVariation = IDL.Variant({
  'accent' : IDL.Null,
  'gradient' : IDL.Null,
  'mono' : IDL.Null,
});
export const ParticleEffect = IDL.Record({
  'enabled' : IDL.Bool,
  'speed' : EffectSpeed,
  'effectType' : ParticleEffectType,
  'intensity' : EffectIntensity,
  'colorVariation' : ColorVariation,
});
export const VectorComplexity = IDL.Variant({
  'complex' : IDL.Null,
  'simple' : IDL.Null,
  'moderate' : IDL.Null,
});
export const VectorEffectType = IDL.Variant({
  'gradientOverlays' : IDL.Null,
  'animatedPaths' : IDL.Null,
  'geometricPatterns' : IDL.Null,
});
export const ColorAccentScheme = IDL.Variant({
  'gradient' : IDL.Null,
  'secondary' : IDL.Null,
  'primary' : IDL.Null,
});
export const VectorEffect = IDL.Record({
  'complexity' : VectorComplexity,
  'enabled' : IDL.Bool,
  'effectType' : VectorEffectType,
  'colorScheme' : ColorAccentScheme,
});
export const HeroSectionTheme = IDL.Record({
  'layoutOverride' : HeroLayoutOverride,
  'gradient' : Gradient,
  'themeType' : ThemeType,
  'areaDimensions' : AreaDimensions,
  'contentPosition' : Position,
  'glassmorphism' : Glassmorphism,
  'spacing' : Spacing,
  'effectsEnabled' : IDL.Bool,
  'colorAccents' : ColorAccents,
  'motionEffect' : MotionEffect,
  'particleEffect' : ParticleEffect,
  'vectorEffect' : VectorEffect,
});
export const ThemePreference = IDL.Variant({
  'dark' : IDL.Null,
  'light' : IDL.Null,
});
export const Button = IDL.Record({ 'link' : IDL.Text, 'text' : IDL.Text });
export const HeroSection = IDL.Record({
  'subtext' : IDL.Text,
  'headline' : IDL.Text,
  'primaryButton' : Button,
  'secondaryButton' : IDL.Opt(Button),
});
export const WebsiteContent = IDL.Record({
  'theme' : ThemePreference,
  'overviewContent' : IDL.Text,
  'heroSection' : HeroSection,
  'doctorCredentials' : DoctorCredentials,
  'aboutContent' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClinic' : IDL.Func([Clinic], [], []),
  'addImage' : IDL.Func([WebsiteImage], [], []),
  'addService' : IDL.Func([Service], [], []),
  'addSocialMediaLink' : IDL.Func([SocialMediaLink], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteClinic' : IDL.Func([IDL.Text], [], []),
  'deleteImage' : IDL.Func([IDL.Text], [], []),
  'deleteService' : IDL.Func([IDL.Text], [], []),
  'deleteSocialMediaLink' : IDL.Func([IDL.Text], [], []),
  'getAllClinics' : IDL.Func([], [IDL.Vec(Clinic)], ['query']),
  'getAllImages' : IDL.Func([], [IDL.Vec(WebsiteImage)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConfig' : IDL.Func([], [Config], ['query']),
  'getDoctorCredentials' : IDL.Func([], [DoctorCredentials], ['query']),
  'getFooterContent' : IDL.Func([], [FooterContent], ['query']),
  'getHeroSectionBackgroundImage' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'darkMode' : IDL.Opt(ExternalBlob),
            'standard' : ExternalBlob,
          })
        ),
      ],
      ['query'],
    ),
  'getHeroSectionTheme' : IDL.Func([], [HeroSectionTheme], ['query']),
  'getImage' : IDL.Func([IDL.Text], [IDL.Opt(WebsiteImage)], ['query']),
  'getSortedSocialMediaLinks' : IDL.Func(
      [],
      [IDL.Vec(SocialMediaLink)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWebsiteContent' : IDL.Func([], [WebsiteContent], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isImageDarkModeCompatible' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClinic' : IDL.Func([Clinic], [], []),
  'updateDoctorCredentials' : IDL.Func([DoctorCredentials], [], []),
  'updateFooterContent' : IDL.Func([FooterContent], [], []),
  'updateHeroSectionTheme' : IDL.Func([HeroSectionTheme], [], []),
  'updateImage' : IDL.Func([WebsiteImage], [], []),
  'updateService' : IDL.Func([Service], [], []),
  'updateSocialMediaLink' : IDL.Func([SocialMediaLink], [], []),
  'updateWebsiteContent' : IDL.Func([WebsiteContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Clinic = IDL.Record({
    'id' : IDL.Text,
    'hours' : IDL.Text,
    'mapLink' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'bookingUrl' : IDL.Opt(IDL.Text),
    'contactDetails' : IDL.Text,
  });
  const WebsiteImage = IDL.Record({
    'id' : IDL.Text,
    'darkModeImage' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const SocialMediaLink = IDL.Record({
    'url' : IDL.Text,
    'displayName' : IDL.Text,
    'order' : IDL.Nat,
    'icon' : IDL.Opt(ExternalBlob),
    'platform' : IDL.Text,
    'iconSize' : IDL.Nat,
    'isVisible' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Config = IDL.Record({ 'terms' : IDL.Text, 'canonicalUrl' : IDL.Text });
  const DoctorCredentials = IDL.Record({
    'yearsOfExperience' : IDL.Text,
    'profileImage' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'qualifications' : IDL.Text,
    'achievements' : IDL.Text,
    'specializations' : IDL.Text,
  });
  const FooterContact = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const FooterLink = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  const FooterContent = IDL.Record({
    'contact' : FooterContact,
    'background' : IDL.Opt(ExternalBlob),
    'quickLinks' : IDL.Vec(FooterLink),
    'copyright' : IDL.Text,
  });
  const VerticalPosition = IDL.Variant({
    'top' : IDL.Null,
    'center' : IDL.Null,
    'bottom' : IDL.Null,
  });
  const TextSizePreset = IDL.Variant({
    'large' : IDL.Null,
    'extraLarge' : IDL.Null,
    'medium' : IDL.Null,
  });
  const MaxWidthPreset = IDL.Variant({
    'full' : IDL.Null,
    'large' : IDL.Null,
    'medium' : IDL.Null,
  });
  const HorizontalAlignment = IDL.Variant({
    'center' : IDL.Null,
    'left' : IDL.Null,
    'right' : IDL.Null,
  });
  const CTARowLayout = IDL.Variant({ 'row' : IDL.Null, 'stacked' : IDL.Null });
  const HeroLayoutOverride = IDL.Record({
    'verticalPlacement' : VerticalPosition,
    'textSizePreset' : TextSizePreset,
    'contentContainerPreset' : MaxWidthPreset,
    'explicitMaxWidth' : IDL.Opt(IDL.Nat),
    'horizontalAlignment' : HorizontalAlignment,
    'ctaRowLayout' : CTARowLayout,
  });
  const Color = IDL.Record({
    'red' : IDL.Nat,
    'blue' : IDL.Nat,
    'green' : IDL.Nat,
  });
  const Gradient = IDL.Record({
    'direction' : IDL.Variant({
      'topToBottom' : IDL.Null,
      'leftToRight' : IDL.Null,
    }),
    'colors' : IDL.Vec(Color),
    'intensity' : IDL.Nat,
  });
  const ThemeType = IDL.Record({
    'accent' : IDL.Variant({
      'magenta' : IDL.Null,
      'blue' : IDL.Null,
      'teal' : IDL.Null,
    }),
    'mode' : IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null }),
    'gradientStyle' : IDL.Variant({ 'radial' : IDL.Null, 'linear' : IDL.Null }),
  });
  const AreaDimensions = IDL.Record({ 'height' : IDL.Nat, 'width' : IDL.Nat });
  const Position = IDL.Record({ 'x' : IDL.Int, 'y' : IDL.Int });
  const Glassmorphism = IDL.Record({
    'transparency' : IDL.Nat,
    'blurIntensity' : IDL.Nat,
    'overlayEffect' : IDL.Variant({
      'strong' : IDL.Null,
      'subtle' : IDL.Null,
      'medium' : IDL.Null,
    }),
  });
  const Spacing = IDL.Record({
    'verticalPadding' : IDL.Nat,
    'elementSpacing' : IDL.Nat,
    'contentAlignment' : IDL.Variant({
      'center' : IDL.Null,
      'left' : IDL.Null,
      'right' : IDL.Null,
    }),
  });
  const ColorAccents = IDL.Record({ 'secondary' : Color, 'primary' : Color });
  const MotionPattern = IDL.Record({
    'complexity' : IDL.Nat,
    'patternType' : IDL.Variant({
      'wave' : IDL.Null,
      'bounce' : IDL.Null,
      'random' : IDL.Null,
      'spiral' : IDL.Null,
    }),
  });
  const MotionAmplitude = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const MotionSpeed = IDL.Variant({
    'fast' : IDL.Null,
    'slow' : IDL.Null,
    'medium' : IDL.Null,
  });
  const MotionEffectType = IDL.Variant({
    'waveMotion' : IDL.Null,
    'floatingMotion' : IDL.Null,
    'wave' : IDL.Null,
    'bounce' : IDL.Null,
    'random' : IDL.Null,
    'spiral' : IDL.Null,
  });
  const MotionEffect = IDL.Record({
    'pattern' : MotionPattern,
    'amplitude' : MotionAmplitude,
    'enabled' : IDL.Bool,
    'speed' : MotionSpeed,
    'effectType' : MotionEffectType,
  });
  const EffectSpeed = IDL.Variant({
    'fast' : IDL.Null,
    'slow' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ParticleEffectType = IDL.Variant({
    'confetti' : IDL.Null,
    'dots' : IDL.Null,
    'crossParticles' : IDL.Null,
    'bubbles' : IDL.Null,
    'lines' : IDL.Null,
    'sparkles' : IDL.Null,
    'swirls' : IDL.Null,
    'stethoscopeParticles' : IDL.Null,
    'rings' : IDL.Null,
  });
  const EffectIntensity = IDL.Variant({
    'dynamic' : IDL.Null,
    'subtle' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const ColorVariation = IDL.Variant({
    'accent' : IDL.Null,
    'gradient' : IDL.Null,
    'mono' : IDL.Null,
  });
  const ParticleEffect = IDL.Record({
    'enabled' : IDL.Bool,
    'speed' : EffectSpeed,
    'effectType' : ParticleEffectType,
    'intensity' : EffectIntensity,
    'colorVariation' : ColorVariation,
  });
  const VectorComplexity = IDL.Variant({
    'complex' : IDL.Null,
    'simple' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const VectorEffectType = IDL.Variant({
    'gradientOverlays' : IDL.Null,
    'animatedPaths' : IDL.Null,
    'geometricPatterns' : IDL.Null,
  });
  const ColorAccentScheme = IDL.Variant({
    'gradient' : IDL.Null,
    'secondary' : IDL.Null,
    'primary' : IDL.Null,
  });
  const VectorEffect = IDL.Record({
    'complexity' : VectorComplexity,
    'enabled' : IDL.Bool,
    'effectType' : VectorEffectType,
    'colorScheme' : ColorAccentScheme,
  });
  const HeroSectionTheme = IDL.Record({
    'layoutOverride' : HeroLayoutOverride,
    'gradient' : Gradient,
    'themeType' : ThemeType,
    'areaDimensions' : AreaDimensions,
    'contentPosition' : Position,
    'glassmorphism' : Glassmorphism,
    'spacing' : Spacing,
    'effectsEnabled' : IDL.Bool,
    'colorAccents' : ColorAccents,
    'motionEffect' : MotionEffect,
    'particleEffect' : ParticleEffect,
    'vectorEffect' : VectorEffect,
  });
  const ThemePreference = IDL.Variant({
    'dark' : IDL.Null,
    'light' : IDL.Null,
  });
  const Button = IDL.Record({ 'link' : IDL.Text, 'text' : IDL.Text });
  const HeroSection = IDL.Record({
    'subtext' : IDL.Text,
    'headline' : IDL.Text,
    'primaryButton' : Button,
    'secondaryButton' : IDL.Opt(Button),
  });
  const WebsiteContent = IDL.Record({
    'theme' : ThemePreference,
    'overviewContent' : IDL.Text,
    'heroSection' : HeroSection,
    'doctorCredentials' : DoctorCredentials,
    'aboutContent' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClinic' : IDL.Func([Clinic], [], []),
    'addImage' : IDL.Func([WebsiteImage], [], []),
    'addService' : IDL.Func([Service], [], []),
    'addSocialMediaLink' : IDL.Func([SocialMediaLink], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteClinic' : IDL.Func([IDL.Text], [], []),
    'deleteImage' : IDL.Func([IDL.Text], [], []),
    'deleteService' : IDL.Func([IDL.Text], [], []),
    'deleteSocialMediaLink' : IDL.Func([IDL.Text], [], []),
    'getAllClinics' : IDL.Func([], [IDL.Vec(Clinic)], ['query']),
    'getAllImages' : IDL.Func([], [IDL.Vec(WebsiteImage)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConfig' : IDL.Func([], [Config], ['query']),
    'getDoctorCredentials' : IDL.Func([], [DoctorCredentials], ['query']),
    'getFooterContent' : IDL.Func([], [FooterContent], ['query']),
    'getHeroSectionBackgroundImage' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'darkMode' : IDL.Opt(ExternalBlob),
              'standard' : ExternalBlob,
            })
          ),
        ],
        ['query'],
      ),
    'getHeroSectionTheme' : IDL.Func([], [HeroSectionTheme], ['query']),
    'getImage' : IDL.Func([IDL.Text], [IDL.Opt(WebsiteImage)], ['query']),
    'getSortedSocialMediaLinks' : IDL.Func(
        [],
        [IDL.Vec(SocialMediaLink)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWebsiteContent' : IDL.Func([], [WebsiteContent], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isImageDarkModeCompatible' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClinic' : IDL.Func([Clinic], [], []),
    'updateDoctorCredentials' : IDL.Func([DoctorCredentials], [], []),
    'updateFooterContent' : IDL.Func([FooterContent], [], []),
    'updateHeroSectionTheme' : IDL.Func([HeroSectionTheme], [], []),
    'updateImage' : IDL.Func([WebsiteImage], [], []),
    'updateService' : IDL.Func([Service], [], []),
    'updateSocialMediaLink' : IDL.Func([SocialMediaLink], [], []),
    'updateWebsiteContent' : IDL.Func([WebsiteContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };