/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AreaDimensions { 'height' : bigint, 'width' : bigint }
export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : Array<RichContentElement>,
  'createdAt' : bigint,
  'author' : string,
  'updatedAt' : bigint,
}
export interface Button { 'link' : string, 'text' : string }
export type CTARowLayout = { 'row' : null } |
  { 'stacked' : null };
export interface Clinic {
  'id' : string,
  'hours' : string,
  'mapLink' : string,
  'name' : string,
  'address' : string,
  'image' : [] | [ExternalBlob],
  'bookingUrl' : [] | [string],
  'contactDetails' : string,
}
export interface Color { 'red' : bigint, 'blue' : bigint, 'green' : bigint }
export type ColorAccentScheme = { 'gradient' : null } |
  { 'secondary' : null } |
  { 'primary' : null };
export interface ColorAccents { 'secondary' : Color, 'primary' : Color }
export type ColorVariation = { 'accent' : null } |
  { 'gradient' : null } |
  { 'mono' : null };
export interface Config { 'terms' : string, 'canonicalUrl' : string }
export interface DoctorCredentials {
  'yearsOfExperience' : string,
  'profileImage' : [] | [ExternalBlob],
  'name' : string,
  'qualifications' : string,
  'achievements' : string,
  'specializations' : string,
}
export type EffectIntensity = { 'dynamic' : null } |
  { 'subtle' : null } |
  { 'moderate' : null };
export type EffectSpeed = { 'fast' : null } |
  { 'slow' : null } |
  { 'medium' : null };
export type ExternalBlob = Uint8Array;
export interface FooterContact {
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface FooterContent {
  'contact' : FooterContact,
  'background' : [] | [ExternalBlob],
  'quickLinks' : Array<FooterLink>,
  'sections' : Array<FooterSection>,
  'copyright' : string,
}
export interface FooterLink { 'url' : string, 'name' : string }
export interface FooterSection {
  'title' : string,
  'content' : string,
  'order' : bigint,
  'divider' : boolean,
}
export interface Glassmorphism {
  'transparency' : bigint,
  'blurIntensity' : bigint,
  'overlayEffect' : { 'strong' : null } |
    { 'subtle' : null } |
    { 'medium' : null },
}
export interface Gradient {
  'direction' : { 'topToBottom' : null } |
    { 'leftToRight' : null },
  'colors' : Array<Color>,
  'intensity' : bigint,
}
export interface HeroLayoutOverride {
  'verticalPlacement' : VerticalPosition,
  'textSizePreset' : TextSizePreset,
  'contentContainerPreset' : MaxWidthPreset,
  'explicitMaxWidth' : [] | [bigint],
  'horizontalAlignment' : HorizontalAlignment,
  'ctaRowLayout' : CTARowLayout,
}
export interface HeroSection {
  'subtext' : string,
  'headline' : string,
  'primaryButton' : Button,
  'secondaryButton' : [] | [Button],
}
export interface HeroSectionTheme {
  'layoutOverride' : HeroLayoutOverride,
  'gradient' : Gradient,
  'themeType' : ThemeType,
  'areaDimensions' : AreaDimensions,
  'contentPosition' : Position,
  'glassmorphism' : Glassmorphism,
  'spacing' : Spacing,
  'effectsEnabled' : boolean,
  'colorAccents' : ColorAccents,
  'motionEffect' : MotionEffect,
  'particleEffect' : ParticleEffect,
  'vectorEffect' : VectorEffect,
}
export interface HomepageTextFormatting {
  'heroHeading' : TextFormattingBundle,
  'footerHeading' : TextFormattingBundle,
  'overviewBody' : TextFormattingBundle,
  'heroBody' : TextFormattingBundle,
  'overviewHeading' : TextFormattingBundle,
  'servicesHeading' : TextFormattingBundle,
  'servicesBody' : TextFormattingBundle,
  'footerBody' : TextFormattingBundle,
}
export type HorizontalAlignment = { 'center' : null } |
  { 'left' : null } |
  { 'right' : null };
export type MaxWidthPreset = { 'full' : null } |
  { 'large' : null } |
  { 'medium' : null };
export type MotionAmplitude = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface MotionEffect {
  'pattern' : MotionPattern,
  'amplitude' : MotionAmplitude,
  'enabled' : boolean,
  'speed' : MotionSpeed,
  'effectType' : MotionEffectType,
}
export type MotionEffectType = { 'waveMotion' : null } |
  { 'floatingMotion' : null } |
  { 'wave' : null } |
  { 'bounce' : null } |
  { 'random' : null } |
  { 'spiral' : null };
export interface MotionPattern {
  'complexity' : bigint,
  'patternType' : { 'wave' : null } |
    { 'bounce' : null } |
    { 'random' : null } |
    { 'spiral' : null },
}
export type MotionSpeed = { 'fast' : null } |
  { 'slow' : null } |
  { 'medium' : null };
export interface ParticleEffect {
  'enabled' : boolean,
  'speed' : EffectSpeed,
  'effectType' : ParticleEffectType,
  'intensity' : EffectIntensity,
  'colorVariation' : ColorVariation,
}
export type ParticleEffectType = { 'confetti' : null } |
  { 'dots' : null } |
  { 'crossParticles' : null } |
  { 'bubbles' : null } |
  { 'lines' : null } |
  { 'sparkles' : null } |
  { 'swirls' : null } |
  { 'stethoscopeParticles' : null } |
  { 'rings' : null };
export interface Position { 'x' : bigint, 'y' : bigint }
export interface RevealAnimation {
  'delayUnit' : bigint,
  'animationType' : { 'pop' : null } |
    { 'fade' : null } |
    { 'none' : null } |
    { 'slideIn' : null } |
    { 'expand' : null },
  'speedUnit' : bigint,
  'easing' : { 'easeInOut' : null } |
    { 'bounce' : null } |
    { 'linear' : null },
}
export interface Review {
  'id' : string,
  'patientImage' : [] | [ExternalBlob],
  'reviewText' : string,
  'patientName' : string,
  'rating' : bigint,
}
export interface ReviewColor {
  'red' : bigint,
  'blue' : bigint,
  'green' : bigint,
}
export interface ReviewContentLayout {
  'style' : { 'glassmorphic' : null } |
    { 'gradient' : null } |
    { 'card' : null } |
    { 'frosted' : null } |
    { 'minimalist' : null },
  'paddingUnit' : bigint,
  'spacingUnit' : bigint,
  'layoutType' : { 'singleColumn' : null } |
    { 'overlay' : null } |
    { 'multiColumn' : null } |
    { 'cardStyle' : null },
}
export type ReviewDisplayMode = { 'multi' : null } |
  { 'centered' : null } |
  { 'single' : null } |
  { 'masonry' : null };
export interface ReviewGlassmorphism {
  'transparency' : bigint,
  'blurIntensity' : bigint,
  'overlayEffect' : { 'strong' : null } |
    { 'subtle' : null } |
    { 'medium' : null },
}
export interface ReviewGradient {
  'direction' : { 'topToBottom' : null } |
    { 'leftToRight' : null } |
    { 'diagonal' : null },
  'colors' : Array<ReviewColor>,
  'intensity' : bigint,
}
export type ReviewTransitionType = { 'glassmorphic' : null } |
  { 'blur' : null } |
  { 'card' : null } |
  { 'fade' : null } |
  { 'none' : null } |
  { 'slide' : null };
export interface ReviewsPanelSettings {
  'revealAnimation' : RevealAnimation,
  'contentLayout' : ReviewContentLayout,
  'displayMode' : ReviewDisplayMode,
  'autoScrollSpeed' : bigint,
  'primaryColor' : ReviewColor,
  'transitionType' : ReviewTransitionType,
  'maxReviews' : bigint,
  'darkModeSupport' : boolean,
  'secondaryColor' : ReviewColor,
  'carouselEnabled' : boolean,
  'gradientSettings' : ReviewGradient,
  'overlayEffect' : ReviewGlassmorphism,
}
export type RichContentElement = {
    'video' : { 'blob' : ExternalBlob, 'description' : string }
  } |
  { 'text' : { 'content' : string } } |
  { 'image' : { 'blob' : ExternalBlob, 'description' : string } };
export interface Service {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface SocialMediaLink {
  'url' : string,
  'displayName' : string,
  'order' : bigint,
  'icon' : [] | [ExternalBlob],
  'platform' : string,
  'iconSize' : bigint,
  'isVisible' : boolean,
}
export interface Spacing {
  'verticalPadding' : bigint,
  'elementSpacing' : bigint,
  'contentAlignment' : { 'center' : null } |
    { 'left' : null } |
    { 'right' : null },
}
export interface TextFormattingBundle {
  'fontFamily' : string,
  'fontWeight' : { 'normal' : null } |
    { 'bold' : null },
  'fontSize' : bigint,
  'letterSpacing' : bigint,
  'textTransform' : { 'none' : null } |
    { 'lowercase' : null } |
    { 'capitalize' : null } |
    { 'uppercase' : null },
}
export type TextSizePreset = { 'large' : null } |
  { 'extraLarge' : null } |
  { 'medium' : null };
export type ThemePreference = { 'dark' : null } |
  { 'light' : null };
export interface ThemeType {
  'accent' : { 'magenta' : null } |
    { 'blue' : null } |
    { 'teal' : null },
  'mode' : { 'dark' : null } |
    { 'light' : null },
  'gradientStyle' : { 'radial' : null } |
    { 'linear' : null },
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VectorComplexity = { 'complex' : null } |
  { 'simple' : null } |
  { 'moderate' : null };
export interface VectorEffect {
  'complexity' : VectorComplexity,
  'enabled' : boolean,
  'effectType' : VectorEffectType,
  'colorScheme' : ColorAccentScheme,
}
export type VectorEffectType = { 'gradientOverlays' : null } |
  { 'animatedPaths' : null } |
  { 'geometricPatterns' : null };
export type VerticalPosition = { 'top' : null } |
  { 'center' : null } |
  { 'bottom' : null };
export interface WebsiteContent {
  'theme' : ThemePreference,
  'overviewContent' : string,
  'heroSection' : HeroSection,
  'doctorCredentials' : DoctorCredentials,
  'aboutContent' : string,
}
export interface WebsiteImage {
  'id' : string,
  'darkModeImage' : [] | [ExternalBlob],
  'description' : string,
  'image' : ExternalBlob,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClinic' : ActorMethod<[Clinic], undefined>,
  'addImage' : ActorMethod<[WebsiteImage], undefined>,
  'addReview' : ActorMethod<[Review], undefined>,
  'addService' : ActorMethod<[Service], undefined>,
  'addSocialMediaLink' : ActorMethod<[SocialMediaLink], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blogExists' : ActorMethod<[string], boolean>,
  'createOrUpdateBlogPost' : ActorMethod<[BlogPost], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteClinic' : ActorMethod<[string], undefined>,
  'deleteImage' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[string], undefined>,
  'deleteSocialMediaLink' : ActorMethod<[string], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllClinics' : ActorMethod<[], Array<Clinic>>,
  'getAllImages' : ActorMethod<[], Array<WebsiteImage>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConfig' : ActorMethod<[], Config>,
  'getDoctorCredentials' : ActorMethod<[], DoctorCredentials>,
  'getFooterContent' : ActorMethod<[], FooterContent>,
  'getHeroSectionBackgroundImage' : ActorMethod<
    [],
    [] | [{ 'darkMode' : [] | [ExternalBlob], 'standard' : ExternalBlob }]
  >,
  'getHeroSectionTheme' : ActorMethod<[], HeroSectionTheme>,
  'getHomepageTextFormatting' : ActorMethod<[], HomepageTextFormatting>,
  'getImage' : ActorMethod<[string], [] | [WebsiteImage]>,
  'getReviewSettings' : ActorMethod<[], ReviewsPanelSettings>,
  'getSortedSocialMediaLinks' : ActorMethod<[], Array<SocialMediaLink>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWebsiteContent' : ActorMethod<[], WebsiteContent>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isImageDarkModeCompatible' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClinic' : ActorMethod<[Clinic], undefined>,
  'updateDoctorCredentials' : ActorMethod<[DoctorCredentials], undefined>,
  'updateFooterContent' : ActorMethod<[FooterContent], undefined>,
  'updateFooterSectionOrder' : ActorMethod<[Array<bigint>], undefined>,
  'updateHeroSectionTheme' : ActorMethod<[HeroSectionTheme], undefined>,
  'updateHomepageTextFormatting' : ActorMethod<
    [HomepageTextFormatting],
    undefined
  >,
  'updateImage' : ActorMethod<[WebsiteImage], undefined>,
  'updateReview' : ActorMethod<[Review], undefined>,
  'updateReviewSettings' : ActorMethod<[ReviewsPanelSettings], undefined>,
  'updateService' : ActorMethod<[Service], undefined>,
  'updateSocialMediaLink' : ActorMethod<[SocialMediaLink], undefined>,
  'updateWebsiteContent' : ActorMethod<[WebsiteContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];